export const filesInitStaete = {};
export const userInitState = {
  isLoggedIn: false,
};

export const applicationsInitState = {
  terminal: {
    key: "terminal",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "terminalWindow",
    appType: "terminal",
    fileType: "",
    isTop: false,
    icon: "terminal.png",
    title: "Terminal",
    className: "terminal-window",
  },
  calc: {
    key: "calc",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "calcWindow",
    appType: "calculator",
    fileType: "",
    isTop: false,
    icon: "calculator.png",
    title: "Calculator",
    className: "calc-window",
  },
  error: {
    key: "error",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "errorWindow",
    appType: "",
    fileType: "",
    isTop: false,
    icon: "stop.png",
    title: "Error Message",
    className: "error-window",
  },
  pdfViewer: {
    key: "pdfViewer",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "pdfApplication",
    appType: "PDF_APP",
    fileType: "PDF",
    isTop: false,
    icon: "pdf.png",
    title: "PDF Document",
    className: "pdf-viewer",
  },
  music: {
    key: "music",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "musicApplication",
    appType: "music",
    fileType: "AUDIO",
    isTop: false,
    icon: "music-sm.png",
    title: "Music Player",
    className: "music-player-container",
  },
  explorer: {
    key: "explorer",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "fileExplorerApplication",
    appType: "FILES_EXPLORER",
    isTop: true,
    icon: "explorer.png",
    className: "FileExplorerContainer",
    title: "Explorer",
  },
  notepad: {
    key: "notepad",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "notepadApplication",
    appType: "NOTEPAD",
    fileType: "TXT",
    isTop: false,
    icon: "notepad2.png",
    className: "notepad",
    title: "Notepad",
  },
  notes: {
    key: "notes",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "notesApplication",
    appType: "NOTES",
    isTop: false,
    icon: "notes.png",
    title: "Notes",
    className: "notes",
  },
  images: {
    key: "images",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "picturesPreviewerApplication",
    appType: "PICTURES_PREVIEWER",
    fileType: "IMAGE",
    isTop: false,
    icon: "photo.png",
    title: "Pictures",
    className: "image-container",
  },
  settings: {
    key: "settings",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "settingsApplication",
    appType: "SETTINGS",
    fileType: undefined,
    isTop: false,
    icon: "settings.png",
    title: "Settings",
    className: "settings-application",
  },
  camera: {
    key: "camera",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "cameraApplication",
    appType: "CAMERA",
    fileType: undefined,
    isTop: false,
    icon: "camera.png",
    title: "Camera",
    className: "camera",
  },

  videoPlayer: {
    key: "videoPlayer",
    isRunning: false,
    zIndex: 0,
    isMinimized: false,
    id: "videoPlayerApplication",
    appType: "VIDEO_PLAYER",
    fileType: "VIDEO",
    isTop: false,
    icon: "video.png",
    title: "Video Player",
    className: "video-player-window",
    src: "",
  },
  progressBar: {
    key: "progressBar",
    isRunning: false,
    zIndex: 10,
    isMinimized: false,
    id: "progressBarApplication",
    appType: "",
    fileType: "",
    isTop: false,
    icon: "marker.png",
    title: "Uploading....",
    className: "progress-bar-window",
  },
};
